bump_version: null
lint: null
nf_core_version: 3.0.0
org_path: null
repository_type: pipeline
template:
  author: Nick Swainston
  description: Pulsar timing data processing pipeline for MeerTime data.
  force: false
  is_nfcore: true
  name: meerpipe
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
